### ISSUE TITLE
Lilith.jl does not install on julia 1.5 + CUDA 1.2.1

### ISSUE THREAD

**Issue by hiro-yoshida** [dfdx/Lilith.jl#18]
Hello,

I like the idea behind the Lilith and wanted to try it out, but it failed to install on julia 1.5 + CUDA 1.2.1 with the following error. 
Are there any way to work around it?

ERROR: Unsatisfiable requirements detected for package GPUArrays [0c68f7d7]:
 GPUArrays [0c68f7d7] log:
 ├─possible versions are: [0.3.0-0.3.4, 0.4.0-0.4.2, 0.5.0, 0.6.0-0.6.1, 0.7.0-0.7.2, 1.0.0-1.0.4, 2.0.0-2.0.1, 3.0.0-3.0.1, 3.1.0, 3.2.0, 3.3.0, 3.4.0-3.4.1, 4.0.0-4.0.1, 5.0.0] or uninstalled
 ├─restricted by compatibility requirements with CUDA [052768ef] to versions: [3.4.0-3.4.1, 4.0.0-4.0.1, 5.0.0]
 │ └─CUDA [052768ef] log:
 │   ├─possible versions are: [0.1.0, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1] or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions [0.1.0, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1]
 └─restricted by compatibility requirements with CuArrays [3a865a2d] to versions: 2.0.0-2.0.1 — no versions left
   └─CuArrays [3a865a2d] log:
     ├─possible versions are: [0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.2, 0.7.0-0.7.3, 0.8.0-0.8.1, 0.9.0-0.9.1, 1.0.0-1.0.2, 1.1.0, 1.2.0-1.2.1, 1.3.0, 1.4.0-1.4.7, 1.5.0, 1.6.0, 1.7.0-1.7.3, 2.0.0-2.0.1, 2.1.0, 2.2.0-2.2.2] or uninstalled
     └─restricted by compatibility requirements with Lilith [94c2ca8e] to versions: [1.5.0, 1.6.0, 1.7.0-1.7.3]
       └─Lilith [94c2ca8e] log:
         ├─possible versions are: 0.1.0 or uninstalled
         └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0

**Comment by dfdx** [comment]
Yep, I'm exactly in the process of adapting Lilith to Julia 1.5 and CUDA (instead of CuArrays + CUDAnative + CUDAapi in previous versions). You can check the progress in [new-tracer](https://github.com/dfdx/Lilith.jl/tree/new-tracer) branch, however be warned that: 

1. CUDA.jl is [not compatible](https://discourse.julialang.org/t/is-it-time-to-migrate-to-cuda-jl/44203) with Julia < 1.4, so the migration introduces a breaking change will takes more time than usually.
2. Next version of Lilith relies on a new version of Yota, which has an unfortunate logging [issue](https://github.com/FluxML/IRTools.jl/issues/78) on Julia 1.5. 

You may try to checkout `new-tracer` branch to try Lilith on Julia 1.5, but for more stable experience I suggest testing it on Julia 1.4 for now.

**Comment by dfdx** [comment]
Lilith has been updated to Julia 1.5, please reopen this issue or create a new one if you encounter any errors.
